const GET_COUNTRIES = 'GET_COUNTRIES'
const ID_COUNTRIES = 'ID_COUNTRIES'
const NAME_COUNTRY = 'NAME_COUNTRY'
const GET_ACTIVITIES = 'GET_ACTIVITIES'
const FILTER_REGION = 'FILTER_REGION'
const FILTER_ACTIVITY = 'FILTER_ACTIVITY'
const SORT_POPULATION = 'FILTER_POPULATION'
const SORT_NAME = 'SORT_NAME'


module.exports = {
    GET_COUNTRIES,
    ID_COUNTRIES,
    NAME_COUNTRY,
    GET_ACTIVITIES,
    FILTER_REGION,
    SORT_POPULATION,
    FILTER_ACTIVITY,
    SORT_NAME
}